/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_duoyi_smallvideolib_YuvHelper */

#ifndef _Included_com_duoyi_smallvideolib_YuvHelper
#define _Included_com_duoyi_smallvideolib_YuvHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_duoyi_smallvideolib_YuvHelper
 * Method:    convertVideoFrame
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;IIIII)I
 */
JNIEXPORT jint JNICALL Java_com_duoyi_smallvideolib_YuvHelper_convertVideoFrame
  (JNIEnv *, jclass, jobject, jobject, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
